import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Download, Upload, FileText, CheckCircle2, AlertCircle, Clock, Pen } from "lucide-react";
import { toast } from "sonner";
import { ContractSignature } from "./ContractSignature";

interface ContractData {
  id: string;
  contract_template_url: string | null;
  signed_contract_url: string | null;
  contract_signed: boolean;
  template_uploaded_at: string | null;
  signed_at: string | null;
  generated_pdf_url: string | null;
  generation_status: string | null;
  contract_data: any;
  digital_signature_creator: string | null;
}

export const CreatorContract = () => {
  const { user } = useAuth();
  const [contract, setContract] = useState<ContractData | null>(null);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [showSignature, setShowSignature] = useState(false);

  useEffect(() => {
    if (user) {
      fetchContract();
    }
  }, [user]);

  const fetchContract = async () => {
    try {
      const { data, error } = await supabase
        .from('creator_contracts')
        .select('*')
        .eq('user_id', user?.id)
        .maybeSingle();

      if (error) throw error;
      setContract(data);
    } catch (error) {
      console.error('Error fetching contract:', error);
      toast.error('Failed to load contract');
    } finally {
      setLoading(false);
    }
  };

  const downloadContract = async (url: string, filename: string) => {
    try {
      const { data, error } = await supabase.storage
        .from('contracts')
        .download(url.replace(`${supabase.storage.from('contracts').getPublicUrl('').data.publicUrl}/`, ''));

      if (error) throw error;

      const blob = new Blob([data]);
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = filename;
      link.click();
      URL.revokeObjectURL(link.href);
      
      toast.success('Contract downloaded');
    } catch (error) {
      console.error('Error downloading contract:', error);
      toast.error('Failed to download contract');
    }
  };

  const handleSignedUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !user) return;

    if (file.type !== 'application/pdf') {
      toast.error('Please upload a PDF file');
      return;
    }

    setUploading(true);
    try {
      const filePath = `${user.id}/signed-contract-${Date.now()}.pdf`;
      
      const { error: uploadError } = await supabase.storage
        .from('contracts')
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('contracts')
        .getPublicUrl(filePath);

      const { error: updateError } = await supabase
        .from('creator_contracts')
        .update({
          signed_contract_url: publicUrl,
          contract_signed: true,
          signed_at: new Date().toISOString(),
        })
        .eq('user_id', user.id);

      if (updateError) throw updateError;

      toast.success('Signed contract uploaded successfully');
      fetchContract();
    } catch (error) {
      console.error('Error uploading signed contract:', error);
      toast.error('Failed to upload signed contract');
    } finally {
      setUploading(false);
    }
  };

  const handleSignatureSubmit = async (signatureData: string) => {
    if (!user || !contract) return;

    try {
      const { error } = await supabase
        .from('creator_contracts')
        .update({
          digital_signature_creator: signatureData,
          contract_signed: true,
          signed_at: new Date().toISOString(),
        })
        .eq('user_id', user.id);

      if (error) throw error;

      toast.success('Contract signed successfully!');
      fetchContract();
    } catch (error) {
      console.error('Error saving signature:', error);
      throw error;
    }
  };

  if (loading) {
    return <div className="flex items-center justify-center p-8">Loading contract...</div>;
  }

  if (!contract || (!contract.contract_template_url && !contract.generated_pdf_url)) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Contract</CardTitle>
          <CardDescription>Your contract will appear here once generated by an administrator</CardDescription>
        </CardHeader>
        <CardContent>
          <Alert>
            <Clock className="h-4 w-4" />
            <AlertDescription>
              Your contract is being prepared. You'll be notified when it's ready to review and sign.
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  // Check if contract is generated but not signed
  const hasGeneratedContract = contract.generated_pdf_url && contract.generation_status === 'generated';
  const isSigned = contract.contract_signed;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Creator Contract
          </CardTitle>
          <CardDescription>
            Review and sign your creator agreement with Bureau Boudoir
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Contract Status */}
          {hasGeneratedContract && !isSigned && (
            <Alert className="border-rose-gold/30 bg-rose-gold/5">
              <AlertCircle className="h-4 w-4 text-rose-gold" />
              <AlertDescription className="text-foreground">
                Your contract is ready for review and signature. Please read through the document carefully before signing.
              </AlertDescription>
            </Alert>
          )}

          {/* Contract Details */}
          {contract.contract_data && (
            <div className="bg-muted/30 border border-border rounded-lg p-4">
              <h3 className="font-semibold text-foreground mb-3">Contract Summary</h3>
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <span className="text-muted-foreground">Revenue Split:</span>
                  <p className="font-medium text-rose-gold">
                    {contract.contract_data.percentage_split_creator}% / {contract.contract_data.percentage_split_agency}%
                  </p>
                </div>
                <div>
                  <span className="text-muted-foreground">Contract Term:</span>
                  <p className="font-medium text-foreground">{contract.contract_data.contract_term_months} months</p>
                </div>
                <div>
                  <span className="text-muted-foreground">Start Date:</span>
                  <p className="font-medium text-foreground">{contract.contract_data.contract_start_date}</p>
                </div>
                <div>
                  <span className="text-muted-foreground">End Date:</span>
                  <p className="font-medium text-foreground">{contract.contract_data.contract_end_date}</p>
                </div>
              </div>
            </div>
          )}

          {/* Generated Contract */}
          {hasGeneratedContract && (
            <div className="border rounded-lg p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-foreground">Your Contract</h3>
                  <p className="text-sm text-muted-foreground">
                    Generated and ready for signature
                  </p>
                </div>
                <Button
                  onClick={() => window.open(contract.generated_pdf_url!, '_blank')}
                  variant="outline"
                  size="sm"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download PDF
                </Button>
              </div>
            </div>
          )}

          {/* Legacy Template (if exists) */}
          {contract.contract_template_url && !hasGeneratedContract && (
            <div className="border rounded-lg p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-foreground">Contract Template</h3>
                  <p className="text-sm text-muted-foreground">
                    Uploaded: {contract.template_uploaded_at 
                      ? new Date(contract.template_uploaded_at).toLocaleDateString()
                      : 'Unknown'}
                  </p>
                </div>
                <Button
                  onClick={() => downloadContract(contract.contract_template_url!, 'contract-template.pdf')}
                  variant="outline"
                  size="sm"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>
          )}

          {/* Signed Status */}
          {isSigned ? (
            <div className="border border-green-200 bg-green-50 dark:bg-green-950 rounded-lg p-4 space-y-3">
              <div className="flex items-center gap-2 text-green-700 dark:text-green-300">
                <CheckCircle2 className="h-5 w-5" />
                <h3 className="font-semibold">Contract Signed ✓</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                Signed on: {new Date(contract.signed_at!).toLocaleDateString()}
              </p>
              {contract.generated_pdf_url && (
                <Button
                  onClick={() => window.open(contract.generated_pdf_url!, '_blank')}
                  variant="outline"
                  size="sm"
                >
                  <Download className="h-4 w-4 mr-2" />
                  View Signed Contract
                </Button>
              )}
            </div>
          ) : hasGeneratedContract ? (
            <div className="border border-rose-gold/30 rounded-lg p-4 space-y-3 bg-rose-gold/5">
              <h3 className="font-semibold text-foreground">Ready to Sign</h3>
              <p className="text-sm text-muted-foreground">
                By signing this contract, you agree to all terms and conditions outlined in the agreement.
              </p>
              <Button
                onClick={() => setShowSignature(true)}
                className="bg-rose-gold hover:bg-rose-gold/90"
              >
                <Pen className="h-4 w-4 mr-2" />
                Sign Contract Digitally
              </Button>
            </div>
          ) : (
            <div className="border rounded-lg p-4 space-y-3">
              <h3 className="font-semibold text-foreground">Upload Signed Contract (Legacy)</h3>
              <p className="text-sm text-muted-foreground">
                Please download the contract, sign it, and upload the signed version here.
              </p>
              <div>
                <input
                  type="file"
                  accept="application/pdf"
                  onChange={handleSignedUpload}
                  disabled={uploading}
                  className="hidden"
                  id="signed-contract-upload"
                />
                <label htmlFor="signed-contract-upload">
                  <Button
                    variant="default"
                    disabled={uploading}
                    asChild
                  >
                    <span>
                      <Upload className="h-4 w-4 mr-2" />
                      {uploading ? 'Uploading...' : 'Upload Signed Contract'}
                    </span>
                  </Button>
                </label>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Signature Modal */}
      <ContractSignature
        open={showSignature}
        onOpenChange={setShowSignature}
        onSignatureSubmit={handleSignatureSubmit}
        contractData={contract.contract_data}
      />
    </div>
  );
};
